<?php

/**
 * Implementation of hook_webform_select_options_info().
 * See webform/webform_hooks.php for further information on this hook in the Webform API.
 */
function mihe_survey_webform_select_options_info() {
    $items = array();
    $items['options1'] = array(
        'title' => t('Options Group 1'),
        'options callback' => '_mihe_survey_options'
    );

   return $items;
}

/**
 * Build an options list to be used with webforms select list based in drupal roles
 */
function _mihe_survey_options() {
//    $roles = user_roles();
//    $contentarray = array();
//    $contentarray[0] = t("Select user role");
//  
//     foreach ($roles as $role) {
//            $contentarray[$role] = t($role);
//      }
//
//    return $contentarray;
    
    $options = array(
        5 => "Definitely agree",
        4 => "Mostly agree", 
        3 => "Neither agree nor disagree", 
        2 => "Mostly disagree",
        1 => "Definitely disagree",
        "NA" => "Not applicable",        
    );
    
    return $options;
    
}


/**
 * Implementation of hook_page_build().
 * .
 */
function mihe_survey_page_build(&$page) {
    
    global $base_url;
    
    //Add logo to the main_top_middle region
    $top_right_logo =  '<img src="'.$base_url.'/'.drupal_get_path('module', 'mihe_survey').'/images/mihe-logo-2.png" />';
    // If there's nothing in the main_top_middle region
    $page['main_top_middle'] = array(
        '#markup' =>$top_right_logo, );   
    
}